# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
